server:
  port: 9922

spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/mytest?characterEncoding=utf8&useSSL=false
    username: root
    password: 1234
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

#mybatis:
  #mapper-locations: classpath:yuanjun/chen/dao/mybatis/mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  #type-aliases-package: yuanjun.chen  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
    
---  
#自定义配置项  
selfprops:
  my:
    country: CHINA
    name: KoKoMal
    slogan: ${selfprops.my.name} Loves ${selfprops.my.country} #注意这里的引用组合
    petname: ${random.value} #随机String值
    petage: ${random.int[1,10]} #随机int
  today:
    temperature: ${random.int[10,40]} #随机温度
  foo: bar # 对应MyPropertiesWithoutAnnotation的foo属性
  database-platform: sql # 对应MyPropertiesWithoutAnnotation的databasPlatform属性
  posts[0]: PLAYBOY # String类型的list
  posts[1]: PLAYGIRL # 同上
  pojo: # 对应复合类型list
    posts[0]:
      title: BREAKING NEWS Alpha
      content: SADDAM was captured
    posts[1]:
      title: BREAKING NEWS Beta
      content: BIN LADEN was shot   
